### ISSUE TITLE
PHP message: PHP Warning:  Array to string conversion in /dokuwiki-test/lib/plugins/charpicker/action.php on line 34

### ISSUE THREAD

**Issue by fiwswe** [turnermm/charpicker#12]
DokuWiki 2022-07-31 "Igor"
PHP 8.0.22 (PHP_FPM called from OpenBSD 7.1 httpd)
[charpicker](https://www.dokuwiki.org/plugin:charpicker) (Last updated on 2020-08-06)

I'm not sure but I suspect it's the `$event->data[$i]['list']` PHP is complaining about.
https://www.dokuwiki.org/devel:event:toolbar_define documents this somewhat sparsely as:
`list — function with options`
That does not sound like an array to me, which is what `array_intersect()` expects.

Note: A `var_dump($event->data[$i]['list']);` would likely help clear this up, but I can't seem to figure out where the output ends up. Or how to properly log from this context…

fiwswe

**Comment by turnermm** [comment]
Should be fixed
